{% set name = "texext" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d103978ba910de4e0a0b03b0ae8cfde28ee5ec4f82bab71603d44c31ff82295d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docutils
    - sphinx

test:
  imports:
    - texext
    - texext.tests

about:
  home: http://github.com/matthew-brett/texext
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE 
  summary: Sphinx extensions for working with LaTeX math
  
  description: |
    texext contains a couple of Sphinx extensions for working with LaTeX math.
  doc_url: https://github.com/matthew-brett/texext
  dev_url: https://github.com/matthew-brett/texext

extra:
  recipe-maintainers:
    - CurtLH
