travis:
  secure:
    BINSTAR_TOKEN: TzVrdBweJAK0bHG8/h5Qjn0wBKvQO7LpP9e8s8rYL8U7qxG13/r7wxePIdrT+I/0hpb/ZhRz0kOY6MPVfdfbZLtPYa9ZiJ/Khlv00B47rgB/wQsM6BAcClG4poCCLv2acAX8TW41tDnc7C6++Mq1Ro/BuHvkJ5ZN/8tHbpr6f4eqSBgkpyZ/D/AFzZGYtaPobdxqXKYrV1FBbqGehLIPNVpIZSz2oodPoqcqXwUk2ueMtgp7MGHoXG+gPhOYrWpfFQDnBU33KWkYWtyVPfkFAU3jiGP3+o7Xd4BwK7EcZOuHjEKfF/j0L4y9ZA1iD+WLsx0ffZdVSAEqrUpZeINo0C59ryJrK03MVotprbtcVmKK2rBNDWgEMRs8H87vDp/vrFWwdzl2Lx09sTo9leES90fNNkSBMCqfRzF/saDboUpbjDsoRyTp20/ScEhFczrQy7ikMNkXgbz/LpogH50zl6raCsgFbq5j98M2NqsFKtdqXyZtjcbmXsrBqbVpvPCkeDV1/P5pESerRuwNmdYVHXhU0PG12hRngvyCkGgyBP5hWVccuEhv8ie0bylbudJY1Rs7b80vOAa3tUaNVfyBouxR+43mfzBkddvtSXSEJyGWbbT3+7pc3Q6eLbT6qMealAYQ4OwQWl6KoHYbfTQThHl+qhSuRDCMXfuXLt8yR8c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
