travis:
  secure:
    BINSTAR_TOKEN: buauhQnEGR8Mlgxh165Sxg1v5zXwky+hd7uHOdBGj4lOR4ss1I/ok80cmGeQg7leHrn+87nkALfLRKDAWy1qmbJozA64kxvPZ7+Co9Ei0IaphppnhvcvQCnTnSpR9hmIGFB9e5znB8E97fabMoePkG16vFNedWOGQz/6oiB/M9WDFKyDHXUPiLaALF10lD5w/RgasQSAEsTwBqW6MNvE+qbNG5eTYW2F/hy24n23r/yl/F2Vm0tno3E92WdubTFMbuEsOOcrAZTk48Xf5vBLQq58SrOv0FESHAS5JAPq+1sxlNbw1Cgi2N2EUdY6eydFlzmaeqzr7zOMOlGNOYjTjIxQhZ00tVS5G7E7i94xGanAPW2IFwG2w1Re4oCGPchhfY4QH2GgzaIB+Bza1xDVOs4+5KckqJjODQaEUX036UHkC9eSetYb4c0GOA7V52hUxPdP7KT1rdd73OOkMut7w1yUUs9+eAV1mVZaeEMXlVbZHPHZqnaRp4XQjnwhQ2ajzD4Bo13QKjCMt9zikwYsk2YxRT5L0gtRXZnuITHixj/LpEml2/FoOLJjXTVByfGPpipKEzEVn2lEsyZt5/QrYOF33+dTZlZWlGzM/+Nzm5Fqz4oX0chPezg5uWgjNIMVIMrwy8Zzoowwz4SQT2ZMpwFoq9cGGk2eEwJ3FQKkXTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
